[tool.black]
line-length = 120

[tool.ruff]
line-length = 120
# Enable Pyflakes `E` and `F` codes by default.
select = [
    "E", "W",  # see: https://pypi.org/project/pycodestyle
    "F",  # see: https://pypi.org/project/pyflakes
]
ignore = ["F841", "E402"]

[tool.isort]
known-first-party = ["lit_gpt"]