precision: bf16-true
devices: 4
resume: false
seed: 1337
data:
  class_path: lit_gpt.data.Deita
  init_args:
    mask_prompt: false
    ignore_index: -1
    seed: 42
    num_workers: 4
    include_multiturn_conversations: false
    download_dir: data/deita
    repo_id: HuggingFaceH4/deita-10k-v0-sft
checkpoint_dir: checkpoints/meta-llama/Llama-2-7b-hf
out_dir: out/finetune/full-llama2-7b-deita
train:
  save_interval: 200
  log_interval: 1
  global_batch_size: 64
  micro_batch_size: 4
  lr_warmup_steps: 25
  epochs: 3
  max_tokens: null
  max_steps: null
  max_seq_length: 1024
  tie_embeddings: null
  learning_rate: 5.0e-05
  weight_decay: 0.02
  beta1: 0.9
  beta2: 0.95
  max_norm: null
  min_lr: 6.0e-05
eval:
  interval: 100
  max_new_tokens: 100
  max_iters: 100
