precision: bf16-true
quantize: bnb.nf4
devices: 1
seed: 1337
lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_query: true
lora_key: false
lora_value: true
lora_projection: false
lora_mlp: false
lora_head: false
data: litgpt.data.Alpaca2k
checkpoint_dir: checkpoints/meta-llama/Llama-2-7b-hf
out_dir: out/finetune/lora-llama2-7b
train:
  save_interval: 200
  log_interval: 1
  global_batch_size: 8
  micro_batch_size: 2
  lr_warmup_steps: 10
  epochs: 4
  max_tokens: null
  max_steps: null
  max_seq_length: 512
  tie_embeddings: null
  learning_rate: 0.0002
  weight_decay: 0.0
  beta1: 0.9
  beta2: 0.95
  max_norm: null
  min_lr: 6.0e-05
eval:
  interval: 100
  max_new_tokens: 100
  max_iters: 100
