precision: bf16-true
devices: 1
resume: false
seed: 1337
data:
  class_path: lit_gpt.data.AlpacaGPT4
  init_args:
    mask_prompt: false
    test_split_fraction: 0.03847
    ignore_index: -1
    seed: 42
    num_workers: 4
    download_dir: data/alpacagpt4
    file_url: https://raw.githubusercontent.com/Instruction-Tuning-with-GPT-4/GPT-4-LLM/main/data/alpaca_gpt4_data.json
    file_name: alpacagpt4_data_cleaned_archive.json
checkpoint_dir: checkpoints/TinyLlama/TinyLlama-1.1B-intermediate-step-1431k-3T
out_dir: out/finetune/full-tinyllama-alpacagpt4
train:
  save_interval: 200
  log_interval: 1
  global_batch_size: 64
  micro_batch_size: 16
  lr_warmup_steps: 100
  epochs: 2
  max_tokens: null
  max_steps: null
  max_seq_length: 512
  tie_embeddings: null
  learning_rate: 5.0e-05
  weight_decay: 0.02
  beta1: 0.9
  beta2: 0.95
  max_norm: null
  min_lr: 6.0e-05
eval:
  interval: 100
  max_new_tokens: 100
  max_iters: 100
